apiVersion: v1
kind: Service
metadata:
    name: bvbpraveenpipelinesjavascriptdocker
spec:
    type: LoadBalancer
    ports:
    - port: 8080 
    selector:
        app: bvbpraveenpipelinesjavascriptdocker